# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 08:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'cart',
                'ordering': ['add_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'order',
                'ordering': ['deal_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='设为热卖')),
                ('is_featured', models.BooleanField(default=False, verbose_name='设为推荐')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('tags', models.CharField(help_text='产品标签，以逗号隔开！', max_length=50)),
                ('desc', models.TextField()),
                ('obj', models.CharField(choices=[('M', 'MAN'), ('W', 'WOMAN')], max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Brands')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('level', models.IntegerField()),
                ('sub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_comment',
                'ordering': ['sub_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='./static/images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Product')),
            ],
            options={
                'db_table': 'product_image',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('pwd', models.CharField(default='88888888', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_exist', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=30)),
                ('birthdate', models.DateField()),
                ('home_num', models.CharField(max_length=40)),
                ('phone_num', models.CharField(max_length=40)),
                ('addr', models.CharField(max_length=100)),
                ('addr_backup', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.User')),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
        migrations.AddField(
            model_name='productcomment',
            name='auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.User'),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.User'),
        ),
        migrations.AddField(
            model_name='cart',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.User'),
        ),
    ]
