# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('home_num', models.CharField(max_length=40)),
                ('phone_num', models.CharField(max_length=40)),
                ('addr', models.CharField(max_length=100)),
                ('addr_backup', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('is_exist', models.IntegerField(default=1)),
            ],
        ),
    ]
