# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20160512_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False, verbose_name='设为热卖'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='设为推荐'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(help_text='产品标签，以逗号隔开！', max_length=50),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='sub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
